gpm failing for some reason

diff --git a/docs/gpm b/docs/gpm
--- a/docs/gpm
+++ b/docs/gpm
@@ -2,12 +2,13 @@
 
 URL="https://raw.githubusercontent.com/sleepless-p03t/genesis6/master/"
 
-# cleanup directory stack at exit 
+# cleanup directory stack at exit and exec bash to register bashrc changes 
 function cleanup
 {
 	while (( $? == 0 )); do
 		popd 2&>1 > /dev/null
 	done
+
 }
 
 # print info message
@@ -356,17 +357,54 @@ function install_core
 			fi
 			mv gpm $HOME/
 		fi
-
-		if [ -f $HOME/.bash_aliases ]; then
-			if ! grep -Fxq '^alias gpm=' $HOME/.bash_aliases; then
-				echo 'alias gpm="bash \"$HOME/gpm\""' >> $HOME/.bash_aliases
-			fi
-		else
-			pinfo "Adding gpm to new .bash_aliases file"
-			echo 'alias gpm="bash \"$HOME/gpm\""' > $HOME/.bash_aliases
-		fi
-		source $HOME/.bash_aliases
 	fi
+
+	echo '_gpmcomplete() {' > $HOME/gpm_complete
+	echo 'COMPREPLY=()' >> $HOME/gpm_complete
+	echo '' >> $HOME/gpm_complete
+	echo 'local margs=("help" "install" "uninstall" "add" "remove" "update" "list")' >> $HOME/gpm_complete
+	echo '' >> $HOME/gpm_complete
+	echo 'declare -A OPTIONS' >> $HOME/gpm_complete
+	echo 'OPTIONS[install]="core all"' >> $HOME/gpm_complete
+	echo 'OPTIONS[add]="all"' >> $HOME/gpm_complete
+	echo 'OPTIONS[remove]="all"' >> $HOME/gpm_complete
+	echo 'OPTIONS[list]="all available installed"' >> $HOME/gpm_complete
+	echo '' >> $HOME/gpm_complete
+	echo 'local cur=${COMP_WORDS[COMP_CWORD]}' >> $HOME/gpm_complete
+	echo '' >> $HOME/gpm_complete
+	echo 'if [ ${OPTIONS[$3]+1} ]; then' >> $HOME/gpm_complete
+	echo 'COMPREPLY=( `compgen -W "${OPTIONS[$3]}" -- $cur` )' >> $HOME/gpm_complete
+	echo 'elif [[ "${OPTIONS[*]}" == *"$3"* ]]; then' >> $HOME/gpm_complete
+	echo 'if [[ "$3" != "all" ]] && [[ "$3" != "core" ]] && [[ "$3" != "available" ]] && [[ "$3" != "installed" ]]; then' >> $HOME/gpm_complete
+	echo 'COMPREPLY=( `compgen -W "${OPTIONS[*]}" -- $cur` )' >> $HOME/gpm_complete
+	echo 'else' >> $HOME/gpm_complete
+	echo 'COMPREPLY=()' >> $HOME/gpm_complete
+	echo 'fi' >> $HOME/gpm_complete
+	echo 'else' >> $HOME/gpm_complete
+	echo 'if [[ "$3" != "help" ]] && [[ "$3" != "update" ]] && [[ "$3" != "uninstall" ]]; then' >> $HOME/gpm_complete
+	echo 'COMPREPLY=( `compgen -W "${margs[*]}" -- $cur` )' >> $HOME/gpm_complete
+	echo 'else' >> $HOME/gpm_complete
+	echo 'COMPREPLY=()' >> $HOME/gpm_complete
+	echo 'fi' >> $HOME/gpm_complete
+	echo 'fi' >> $HOME/gpm_complete
+	echo '}' >> $HOME/gpm_complete
+	echo 'complete -F _gpmcomplete gpm' >> $HOME/gpm_complete
+		
+	if [ -f $HOME/.bash_aliases ]; then
+		if ! grep -Fxq '^alias gpm=' $HOME/.bash_aliases; then
+			echo 'alias gpm="bash \"$HOME/gpm\""' >> $HOME/.bash_aliases
+		fi
+
+		if ! grep -Fxq '^source $HOME/gpm_complete' $HOME/.bash_aliases; then
+			echo 'source $HOME/gpm_complete' >> $HOME/.bash_aliases
+		fi
+	else
+		pinfo "Adding gpm to new .bash_aliases file"
+		echo 'alias gpm="bash \"$HOME/gpm\""' > $HOME/.bash_aliases
+		echo 'source $HOME/gpm_complete' >> $HOME/.bash_aliases
+	fi
+	cat $HOME/.bash_aliases | sort -u > $HOME/.temp
+	mv $HOME/.temp $HOME/.bash_aliases
 }
 
 function update
@@ -563,26 +601,28 @@ elif [[ "$1" == "uninstall" ]]; then
 		pinfo "Removing genesis exec script"
 		rm /usr/local/bin/genesis
 	fi
-	
+	# if gpm not removed, remove it
 	if [ -f $HOME/gpm ]; then
 		read -r -p "Do you want to remove gpm as well? [Y/n]: " -n 1
 		echo
 		if [[ $REPLY =~ ^[Yy]$ ]]; then
 			pinfo "Removing gpm"
-			rm $HOME/gpm
-			if [ -f $HOME/.bash_aliases ]; then
-				pinfo "Removing alias gpm"
-				if grep -Fxq '^alias gpm=' $HOME/.bash_aliases; then
-					if [[ $(grep -v '^alias gpm' | nl | awk '{ print $1 }') != "" ]]; then
-						sed -i '/^alias gpm=/d' $HOME/.bash_aliases
-					else
-						pinfo "No other aliases found in .bash_aliases"
-						pinfo "Removing .bash_aliases file"
-						rm $HOME/.bash_aliases
-					fi
-				fi
+			if [ -f $HOME/gpm ]; then
+				rm $HOME/gpm
 			fi
-			source $HOME/.bash_aliases
+			
+			# remove completion script
+			if [ -f $HOME/gpm_complete ]; then
+				rm $HOME/gpm_complete
+			fi
+			
+			# update .bash_aliases
+			if [ -f $HOME/.bash_aliases ]; then
+				grep -v 'gpm' $HOME/.bash_aliases > $HOME/.temp
+				mv $HOME/.temp $HOME/.bash_aliases
+			fi
+			# remove completion
+			complete -r gpm
 		fi
 	fi
 # unknown command
